FROM node:23-alpine

WORKDIR /app

COPY package.json ./
COPY package-lock.json* ./


# Install dependencies
RUN npm install -g pnpm
RUN pnpm install

# Copy the rest of the frontend code
COPY . .


# Expose port
EXPOSE 3000

# Command to start development server
CMD ["pnpm", "dev", "--host", "0.0.0.0"]